id: P7332CF27
initial_creation_type: ocr
source_metadata:
  volumes:
    21d6294329ec4588a666ad371b31c363:
      base_file: v065.txt
      image_group_id: I1PD95910
      title: སངས་རྒྱས་རྗེས་སུ་དྲན་པའི་རྒྱ་ཆེར་འགྲེལ་པ།
      total_pages: 1498
      volume_number: 65
